version: "3.9"

services:
  master:
    env_file:
      - .env.test
    image: bitnami/postgresql:16
    container_name: postgres-master
    restart: always
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=${DB_SLAVE_USERNAME}
      - POSTGRESQL_REPLICATION_PASSWORD=${DB_SLAVE_PASSWORD}
      - POSTGRESQL_USERNAME=${DB_USERNAME}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE=${DB_DATABASE}
    ports:
      - "${DB_PORT}:5432"

  slave:
    env_file:
      - .env.test
    image: bitnami/postgresql:16
    container_name: postgres-slave
    restart: always
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=${DB_SLAVE_USERNAME}
      - POSTGRESQL_REPLICATION_PASSWORD=${DB_SLAVE_PASSWORD}
      - POSTGRESQL_MASTER_HOST=master
      - POSTGRESQL_MASTER_PORT_NUMBER=${DB_PORT}
      - POSTGRESQL_USERNAME=${DB_USERNAME}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
    depends_on:
      - master
    ports:
      - "${DB_SLAVE_PORT}:5432"
