CREATE SCHEMA admin;
CREATE SCHEMA app;

GRANT ALL PRIVILEGES ON SCHEMA admin TO slave;
ALTER DEFAULT PRIVILEGES IN SCHEMA admin GRANT ALL ON TABLES TO slave;

GRANT ALL PRIVILEGES ON SCHEMA app TO slave;
ALTER DEFAULT PRIVILEGES IN SCHEMA app GRANT ALL ON TABLES TO slave;