name: Pull request

on:
  push:
    branches:
      - main
      - dev
      - pr-test
  pull_request:
    branches:
      - "**"

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [ 20 ]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: npm run test:report

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: test-results
          path: junit.xml
          fail-on-error: 'true'
          reporter: jest-junit
          token: ${{ secrets.GITHUB_TOKEN }}