name: Pull request

on:
  push:
    branches:
      - main
      - dev
      - pr-test
  pull_request:
    branches:
      - "**"

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: npm run test:report

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: test-results
          path: junit.xml
          fail-on-error: 'false'
          reporter: jest-junit
          token: ${{ secrets.GITHUB_TOKEN }}